function [FunHand,qdot] = dynamics_spring()
% I'm defining q here to be [theta, phi, thetadot, phidot]
% 
% Inputs:   q     = States
%           beta  = Ratio of foot mass to body mass (m/M)
%           gamma = Ramp angle (rad)
%           L     = Length of the legs

    g=9.81; %[m/s^2] acceleration due to gravity
    
  %  theta  = q(1);
  %  phi    = q(2);
  %  thetaD = q(3);
  %  phiD   = q(4);
    alpha = 1;
    beta = 1;
    delta = 1;
    d_alpha =1;
    d_beta=1;
    d_delta = 1;
    L = 10;
    M = 10;
    m = 8;
    k = 500;
    
deltaDD = (L.^2.*((-7).*m.^2+(-18).*m.*M+(-8).*M.^2+3.*m.^2.*cos(2.*beta))+...
(-4).*L.*((-5).*m.^2+(-10).*m.*M+(-4).*M.^2+m.^2.*cos(2.*beta)).*...
delta+(-8).*(2.*m.^2+3.*m.*M+M.^2).*delta.^2).^(-1).*((-4).*delta...
.^3.*(k.*((-3).*m+(-2).*M+m.*cos(2.*beta))+2.*(2.*m.^2+3.*m.*M+...
M.^2).*d_alpha.^2)+2.*delta.^2.*(L.*(15.*m.^2+30.*m.*M+...
12.*M.^2+2.*m.*(m+M).*cos(beta)+(-1).*m.^2.*cos(2.*beta)).*...
d_alpha.^2+4.*L.*m.*(m+M).*cos(beta).*d_alpha...
.*d_beta+2.*(2.*k.*L.*m.*cos(2.*beta)+(-2).*(m+M)...
.*(2.*k.*L+g.*(2.*m+M).*sin(alpha))+L.*m.*(m+M).*cos(beta).*...
d_beta.^2))+L.^2.*(g.*((-1).*(7.*m.^2+18.*m.*M+8.*...
M.^2).*sin(alpha)+m.^2.*(sin(alpha+(-2).*beta)+2.*sin(alpha+2.*beta))...
)+L.*(4.*m.^2+14.*m.*M+8.*M.^2+m.*(m+4.*M).*cos(beta)+(-1).*m.^2.*...
cos(2.*beta)).*d_alpha.^2+L.*m.*(m+4.*M).*cos(beta).* ...
d_beta.^2+2.*m.*cos(beta).*d_alpha.*(L.*(...
m+4.*M).*d_beta+(-2).*m.*sin(beta).*d_delta))...
+(-1).*L.*delta.*((-6).*k.*L.*m+(-8).*k.*L.*M+4.*k.*L.*m.*cos(...
2.*beta)+(-20).*g.*m.^2.*sin(alpha)+(-40).*g.*m.*M.*sin(alpha)+(-16)...
.*g.*M.^2.*sin(alpha)+g.*m.^2.*sin(alpha+(-2).*beta)+3.*g.*m.^2.*...
sin(alpha+2.*beta)+L.*(19.*m.^2+50.*m.*M+24.*M.^2+4.*m.*(m+2.*M).*...
cos(beta)+(-3).*m.^2.*cos(2.*beta)).*d_alpha.^2+4.*L.*...
m.*(m+2.*M).*cos(beta).*d_beta.^2+8.*m.*cos(beta).*...
d_alpha.*(L.*(m+2.*M).*d_beta+(-1).*m.*...
sin(beta).*d_delta)))

alphaDD = (-2).*(L.^2.*((-7).*m.^2+(-18).*m.*M+(-8).*M.^2+3.*m.^2.*cos(2.*...
beta))+(-4).*L.*((-5).*m.^2+(-10).*m.*M+(-4).*M.^2+m.^2.*cos(2.*beta...
)).*delta+(-8).*(2.*m.^2+3.*m.*M+M.^2).*delta.^2).^(-1).*(2.*k.*...
m.*sin(2.*beta).*delta.^2+delta.*(8.*g.*m.^2.*cos(alpha)+12.*g.*m.*...
M.*cos(alpha)+4.*g.*M.^2.*cos(alpha)+(-2).*k.*L.*m.*sin(2.*beta)+(...
-2).*L.*m.*(m+M+m.*cos(beta)).*sin(beta).*d_alpha.^2+(...
-2).*L.*m.*(m+M).*sin(beta).*d_beta.^2+(-4).*(m+M).*...
d_alpha.*(L.*m.*sin(beta).*d_beta+2.*(2.*...
m+M).*d_delta))+L.*(g.*cos(alpha).*((-5).*m.^2+(-10).*...
m.*M+(-4).*M.^2+m.^2.*cos(2.*beta))+2.*L.*m.*(m+M+m.*cos(beta)).*...
sin(beta).*d_alpha.^2+2.*L.*m.*(m+M).*sin(beta).*...
d_beta.^2+2.*d_alpha.*(2.*L.*m.*(m+M).*...
sin(beta).*d_beta+(5.*m.^2+10.*m.*M+4.*M.^2+(-1).*...
m.^2.*cos(2.*beta)).*d_delta)))
%If something is wrong, I can try to rewrite this one
betaDD = 2.*L.^(-1).*(L.^2.*((-7).*m.^2+(-18).*m.*M+(-8).*M.^2+3.*m.^2.*...
cos(2.*beta))+(-4).*L.*((-5).*m.^2+(-10).*m.*M+(-4).*M.^2+m.^2.*...
cos(2.*beta)).*delta+(-8).*(2.*m.^2+3.*m.*M+M.^2).*delta.^2).^(-1).*...
((-8).*k.*(2.*m+M).*sin(beta).*delta.^3+4.*L.*sin(beta).*delta.^2.*(...
k.*(6.*m+4.*M+m.*cos(beta))+m.*(2.*m+M).*d_alpha.^2)+(...
-2).*L.*delta.*((-4).*g.*m.^2.*cos(alpha)+(-6).*g.*m.*M.*cos(alpha)+(...
-2).*g.*M.^2.*cos(alpha)+(-4).*g.*m.^2.*cos(alpha).*cos(beta)+(-2).*...
g.*m.*M.*cos(alpha).*cos(beta)+5.*k.*L.*m.*sin(beta)+4.*k.*L.*M.*...
sin(beta))+k.*L.*m.*sin(2.*beta)+L.*m.*(7.*m+5.*M+3.*m.*cos(beta))...
.*sin(beta).*d_alpha.^2+L.*m.*(m+M+2.*m.*cos(beta)).*...
sin(beta).*d_beta.^2+2.*d_alpha.*(L.*m.*(...
m+M+2.*m.*cos(beta)).*sin(beta).*d_beta+2.*(2.*m+M).*...
(m+M+m.*cos(beta)).*d_delta))+L.^2.*((-1).*g.*cos(alpha...
).*(5.*m.^2+10.*m.*M+4.*M.^2+2.*m.*(2.*m+M).*cos(beta)+(-1).*...
m.^2.*cos(2.*beta))+L.*m.*(7.*m+6.*M+5.*m.*cos(beta)).*sin(beta).*...
d_alpha.^2+L.*m.*(2.*(m+M)+3.*m.*cos(beta)).*sin(beta)...
.*d_beta.^2+d_alpha.*(2.*L.*m.*(2.*(m+M)+...
3.*m.*cos(beta)).*sin(beta).*d_beta+2.*(5.*m.^2+10.*...
m.*M+4.*M.^2+2.*m.*(2.*m+M).*cos(beta)+(-1).*m.^2.*cos(2.*beta)).*...
d_delta))



    
   % alphaDD = 
    
   % betaDD = 
    
    
 
    

    %qdot = [thetaD; phiD; thetaDD; phiDD];
    
    qdot = 1;
    
    %Function Handle
    
    %FunHand = @(t,q)[ q(3);...
%                     q(4);...
%                    (1/(1+2*beta*(1-cos(q(2)))-beta*(1-cos(q(2)))))*...
%                    (beta*sin(q(2))*(q(4)^2-2*q(3)*q(4))...
%                       - (beta*g/L)*(sin(q(1)-q(2)-gamma) - sin(q(1)-gamma))...
%                       + (g/L)*sin(q(1)-gamma));...
%                     (1/(beta*(1-cos(q(2)))-beta))*...
%                     (-beta*q(3)^2*sin(q(2)) - (beta*g/L)*sin(q(1)-q(2)-gamma))];
       
FunHand = 1;

end

%Copy of betaDD pre processing
% [2.*L.^(-1).*(L.^2.*((-7).*m.^2+(-18).*m.*M+(-8).*M.^2+3.*m.^2.* ...
%  \
%  cos(2.*\[Beta](t)))+(-4).*L.*((-5).*m.^2+(-10).*m.*M+(-4).*M.^2+m.^2.\
% * ...
%   cos(2.*\[Beta](t))).*\[Delta](t)+(-8).*(2.*m.^2+3.*m.*M+M.^2).\
% *\[Delta](t).^2).^(-1).* ...
%   ((-8).*k.*(2.*m+M).*sin(\[Beta](t)).*\
% \[Delta](t).^3+4.*L.*sin(\[Beta](t)).*\[Delta](t).^2.*( ...
%   \
% k.*(6.*m+4.*M+m.*cos(\[Beta](t)))+m.*(2.*m+M).*Derivative(1)(\[Alpha])\
% (t).^2)+( ...
%   \
% -2).*L.*\[Delta](t).*((-4).*g.*m.^2.*cos(\[Alpha](t))+(-6).*g.*m.*M.*\
% cos(\[Alpha](t))+( ...
%   \
% -2).*g.*M.^2.*cos(\[Alpha](t))+(-4).*g.*m.^2.*cos(\[Alpha](t)).*cos(\
% \[Beta](t))+(-2).* ...
%   \
% g.*m.*M.*cos(\[Alpha](t)).*cos(\[Beta](t))+5.*k.*L.*m.*sin(\[Beta](t))\
% +4.*k.*L.*M.* ...
%   \
% sin(\[Beta](t))+k.*L.*m.*sin(2.*\[Beta](t))+L.*m.*(7.*m+5.*M+3.*m.*\
% cos(\[Beta](t))) ...
%   \
% .*sin(\[Beta](t)).*Derivative(1)(\[Alpha])(t).^2+L.*m.*(m+M+2.*m.*cos(\
% \[Beta](t))).* ...
%   \
% sin(\[Beta](t)).*Derivative(1)(\[Beta])(t).^2+2.*Derivative(1)(\
% \[Alpha])(t).*(L.*m.*( ...
%   \
% m+M+2.*m.*cos(\[Beta](t))).*sin(\[Beta](t)).*Derivative(1)(\[Beta])(t)\
% +2.*(2.*m+M).* ...
%   \
% (m+M+m.*cos(\[Beta](t))).*Derivative(1)(\[Delta])(t)))+L.^2.*((-1).*g.\
% *cos(\[Alpha](t) ...
%   \
% ).*(5.*m.^2+10.*m.*M+4.*M.^2+2.*m.*(2.*m+M).*cos(\[Beta](t))+(-1).* ...
% \
%   m.^2.*cos(2.*\[Beta](t)))+L.*m.*(7.*m+6.*M+5.*m.*cos(\[Beta](t))).*\
% sin(\[Beta](t)).* ...
%   \
% Derivative(1)(\[Alpha])(t).^2+L.*m.*(2.*(m+M)+3.*m.*cos(\[Beta](t))).*\
% sin(\[Beta](t)) ...
%   .*Derivative(1)(\[Beta])(t).^2+Derivative(1)(\
% \[Alpha])(t).*(2.*L.*m.*(2.*(m+M)+ ...
%   3.*m.*cos(\[Beta](t))).*sin(\
% \[Beta](t)).*Derivative(1)(\[Beta])(t)+2.*(5.*m.^2+10.* ...
%   \
% m.*M+4.*M.^2+2.*m.*(2.*m+M).*cos(\[Beta](t))+(-1).*m.^2.*cos(2.*\
% \[Beta](t))).* ...
%   Derivative(1)(\[Delta])(t))))];